[[theme]]
id = "catppuccin-mocha"
name = "Catppuccin Mocha"
appearance = "dark"
background = "#1e1e2e"
foreground = "#cdd6f4"
cursor = "#f5e0dc"
cursor-text = "#1e1e2e"
selection = "#585b70"
selection-text = "#cdd6f4"
accent = "#cba6f7"
palette = [
  "#45475a", "#f38ba8", "#a6e3a1", "#f9e2af",
  "#89b4fa", "#f5c2e7", "#94e2d5", "#bac2de",
  "#585b70", "#f38ba8", "#a6e3a1", "#f9e2af",
  "#89b4fa", "#f5c2e7", "#94e2d5", "#a6adc8",
]
